services:
  postgres:
    container_name: postgres-639
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'admin'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
  
  pgadmin:
    container_name: pgadmin-639
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@639.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - 5433:80
    depends_on:
      - postgres
  
  api:
    container_name: api-639
    image: api-639
    build: ./api
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  nginx:
    container_name: nginx-639
    image: nginx-639
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - api
    
volumes:
  database:

networks:
  default:
    name: 639-network
